### ISSUE TITLE
TVDB support for TV Shows

### ISSUE THREAD

**Issue by sfintel** [milaq/kodi-headless#15]
I've been having issues getting kodi-headless to add new TV Shows to the database. I discovered that TV Shows use TMDB as the information provider. Shouldn't TV Shows use TVDB?

**Comment by milaq** [comment]
Hi,

we use the default scraper configuration that ships with upstream Kodi.

Since some time now, the default TV show scraper is TMDB afaik.
Nevertheless, we configure nothing in that regard.

I also went ahead and changed the wording in the readme to avoid confusion.
https://github.com/milaq/kodi-headless/commit/5a1cce4824cb00ea0b17b9fb0f84827b45537612

Cheers
